# Generated by Django 4.2.1 on 2023-09-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ArticleName')),
                ('content', models.TextField(max_length=1000)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gym.clubcard', verbose_name='DiscountCard'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='photos/lessons', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject_name',
            field=models.CharField(choices=[('swim', 'Swimming'), ('bobu', 'BoduBuilding'), ('yoga', 'Yoga'), ('dance', 'Dancing'), ('karate', 'Karate'), ('gymn', 'Gymnastics'), ('judo', 'Judo'), ('box', 'Boxing')], max_length=50, verbose_name='SubjectName'),
        ),
        migrations.AlterField(
            model_name='master',
            name='subject_name',
            field=models.CharField(choices=[('swim', 'Swimming'), ('bobu', 'BoduBuilding'), ('yoga', 'Yoga'), ('dance', 'Dancing'), ('karate', 'Karate'), ('gymn', 'Gymnastics'), ('judo', 'Judo'), ('box', 'Boxing')], default='NoneSubject', max_length=20, verbose_name='SubjectName'),
        ),
    ]
