# Generated by Django 4.2.1 on 2023-10-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/vacancy_labels'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
