# Generated by Django 4.2.1 on 2023-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_article_alter_client_card_alter_lesson_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='DataTime')),
                ('question', models.TextField(max_length=500, verbose_name='QuestionContent')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
