# Generated by Django 4.2.1 on 2023-09-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_question_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=3000, null=True, verbose_name='QuestionAnswer'),
        ),
    ]
