# Generated by Django 4.2.1 on 2023-09-10 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Оценка не может быть отрицательной'), django.core.validators.MaxValueValidator(10, message='Оценка не может быть больше 10')])),
                ('text.txt', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='DataTime')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='DataTime'),
        ),
    ]
