# Generated by Django 4.2.1 on 2023-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_review_article_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time',
        ),
        migrations.AddField(
            model_name='clubcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='card_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
